---
- name: nginx | Ensure the PGP key is installed
  apt_key: id=AC40B2F7 state=present url="http://keyserver.ubuntu.com/pks/lookup?op=get&fingerprint=on&search=0x561F9B9CAC40B2F7"

- name: nginx | add ppa for latest
  action: apt_repository repo=ppa:nginx/stable

- name: nginx | update apt
  command: sudo apt-get update

- name: nginx | install apt packages
  apt: pkg={{ item }} state=present
  with_items:
   - apt-transport-https
   - nginx-full

- name: nginx | delete default vhost
  action: file path=/etc/nginx/sites-enabled/default state=absent
  notify:
    - restart nginx

- name: nginx | configure host
  template: src=nerdtrack.nginx.j2 dest=/etc/nginx/sites-enabled/nerdtrack
  notify:
    - restart nginx

- name: nginx | ensure nginx is running
  service: name=nginx state=started



